version: "2"
services:
  database:
    image: postgres:9.6.1
    restart: always
    env_file:
      - dev.env
    ports:
      - "2345:5432"

    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-03/personal-projects/forecasting-tool:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "8888:8000"
      - "7777:22"
      - "3030:3000"
    command: "/usr/sbin/sshd -D"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./app:/app
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./scripts:/scripts

volumes:
  database:
